### ISSUE TITLE
Validation message

### ISSUE THREAD

**Issue by L-Luciano** [diegocosta/aor-ckeditor-input#1]
Hi, 

Can you think to manage meta and error props from admin on rest to customize the input ?

Regards

**Comment by diegocosta** [comment]
Hello @L-Luciano, update your `aor-ckeditor-input` to 1.2.0 version and follow this example:

```js
import CKEditor from 'aor-ckeditor-input';

const required = value => value ? undefined : 'This field is required';

const MyPageCreate = () => (
    <CKEditor source="description" validate={required} />
)
```
and you can apply some styles using `.aor-ckeditor-input .error` css class.

I hope this will help you.
